sudo: false
language: go
go:
- 1.5.3
script:
- go test ./cmd/generate
- go test ./cmd/ieuser
- go test ./cmd/uploadfhir
- go test ./cmd/uploadhds
branches:
  only:
  - master
notifications:
  slack:
    secure: RZJssxt+qqVhNk7E3a96NVWoncfua7yz7ojAeQ890oY4cTiWJ3NTd5yUXhfmGpP5G7eD8mU4UpxyfjmK2Dz38D+4GAodY9DGecHD4B/d29L8JjVZDVfV3PuFccHBioubg6A97S7TQwTAmjFgjf51yHVThPRw/zG05P265C02lWM=
