sudo: false
language: go
go:
- 1.6
script: go test $(go list ./... | grep -v /vendor/)
install: true
branches:
  only:
  - master
notifications:
  slack:
    secure: RZJssxt+qqVhNk7E3a96NVWoncfua7yz7ojAeQ890oY4cTiWJ3NTd5yUXhfmGpP5G7eD8mU4UpxyfjmK2Dz38D+4GAodY9DGecHD4B/d29L8JjVZDVfV3PuFccHBioubg6A97S7TQwTAmjFgjf51yHVThPRw/zG05P265C02lWM=
